---

- hosts: all
  roles:
  - role: jpic.pacman
    pacman_mirrors:
    - http://arch.yourlabs.org/
    pacman_repositories:
    - name: repo-ck
      url: http://ck.yourlabs.org/$arch
    archlinux_keys:
    - 5EE46C4C
  - jpic.march
  - jpic.ck
  - jpic.squid
  - role: .
    vagrant_http_proxy: http://10.0.2.2:3128
