Vagrant.configure("2") do |config|
  {% if vagrant_http_proxy %}

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "{{ vagrant_http_proxy }}"
    config.proxy.https    = "{{ vagrant_http_proxy }}"
    config.proxy.no_proxy = "localhost,127.0.0.1"
  end

  {% endif %}

  config.ssh.insert_key = {{ vagrant_config_ssh_insert_key }}
end
